const PUBLISHERS_LIST_PATH = "/publishers";
const PUBLISHERS_NEW_PATH = `${PUBLISHERS_LIST_PATH}/new`;
const PUBLISHERS_EDIT_PATH = `${PUBLISHERS_LIST_PATH}/edit/:id`;

export default {
  PUBLISHERS_LIST_PATH,
  PUBLISHERS_NEW_PATH,
  PUBLISHERS_EDIT_PATH,
};
